const appointmentsData = [
    {
      id: 1,
      name: 'Cy Ganderton',
      date: '12/16/2020',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Paid',
    },
    {
      id: 2,
      name: 'Hart Hagerty',
      date: '12/16/2023',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Pending',
    },
    {
      id: 3,
      name: 'Hart Hagerty',
      date: '12/16/2020',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Pending',
    },
    {
      id: 4,
      name: 'Hart Hagerty',
      date: '12/16/2021',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Paid',
    },
    {
      id: 5,
      name: 'Hart Hagerty',
      date: '12/16/2023',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Pending',
    },
    {
      id: 6,
      name: 'Hart Hagerty',
      date: '12/16/2020',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Paid',
    },
    {
      id: 7,
      name: 'Hart Hagerty',
      date: '12/09/2023',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Pending',
    },
    {
      id: 8,
      name: 'Hart Hagerty',
      date: '12/16/2020',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Pending',
    },
    {
      id: 9,
      name: 'Hart Hagerty',
      date: '12/16/2020',
      time: '06:41 pm',
      treatment: 'Cavity Protection',
       price: "$15",
      paymentStatus: 'Paid',
    },
    // Add more appointment objects as needed
  ];

  export default appointmentsData;
